[meta]
version = "0.1.0"

[project]
name = "hamt_py"
package = "hamt"
main_lang = "py"
version = "0.1.16"
version_date = "2018-03-02"
author = "Jim Dixon"
author_email = "jddixon@gmail.com"
description = "generator for hamt_py projects"
copyright = "2017"
dev_status = "pre-alpha"
license = "mit"
relpath = "py/hamt_py"
state = "shared"
url = "https://jddixon.github.io/hamt_py"

[py]
packages = [ "hamt",]
package_dir = [ "src",]
test_dir = "tests"
py_modules = []
scripts = []
ext_modules = []
distshare = [ "rnglib", "xlutil_py",]
requirements = [ "setuptools",]
test_requirements = []
